allow `deft-directory' to be nil
and work less hard to ensure that it is set at all times,
or that it is set to a properly chosen value; it is just
the default location for new notes (in the Xapian case)

also:
- fix a "search" command error, where if there are
  no databases, then the end result is the C++ exception:
    InvalidArgumentError: Can't make an Enquire object from
    an uninitialised Database object.